version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: cesizen-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: ./CesiZenApi
    container_name: cesizen-api
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - ./CesiZenApi:/app
    environment:
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    env_file:
      - .env

  web:
    build: ./CesiZenWebSite
    container_name: cesizen-web
    ports:
      - "5173:5173"
    volumes:
      - ./CesiZenWebSite:/app
    depends_on:
      - api

volumes:
  mysql_data:
